src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(
     *     max = 50,
     *     maxMessage = "Le titre ne doit pas faire plus de 50 caractères"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(
     *     min = 10,
     *     minMessage = "Le contenu doit faire au moins 10 caractères"
     * )
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_publi;

    /**
     * on indique à doctrine que cette propriété fait référence à
     * l'entité User et qu'il s'agit d'une relation ManyToOne
     *
     * on rajoute inversedBy
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @Assert\Image
     */
    private $image;

    /**
     * Relation ManyToMany :un article peut avoir plusieurs tags
     * et un tag peut être associé à plusieurs articles
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="articles")
     * @ORM\JoinTable(name="articles_tags",
     *      joinColumns={@ORM\JoinColumn(name="article_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="tag_id", referencedColumnName="id")})
     */
    private $tags;

    public function __construct() {
        $this->tags = new ArrayCollection();
    }


    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDatePubli(): ?\DateTimeInterface
    {
        return $this->date_publi;
    }

    public function setDatePubli(?\DateTimeInterface $date_publi): self
    {
        $this->date_publi = $date_publi;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag)
    {
        //Article est le côté "propriétaire" de la relation
        $tag->addArticle($this); // on met à jour l'autre côté de la relation ManyToMany
        $this->tags[] = $tag;
    }
}

src/Form/ArticleType.php
<?php
/**
 * Created by PhpStorm.
 * User: Matthieu
 * Date: 11/05/2018
 * Time: 19:07
 */

namespace App\Form;


use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, array('label'=>'Titre de l\'article'))
            ->add('content', TextareaType::class, array('label'=>'Contenu de l\'article'))
            ->add('image', FileType::class, array('label' => 'image descriptive', 'required' => false))
            ->add('tags', EntityType::class, array('class' => Tag::class, 'multiple' => true, 'required'=>false))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'inherit_data' => true,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

// ce use nous permet d'utiliser new Article() dans ce namespace
use App\Entity\Article;

use App\Form\ArticleUserType;
use App\Service\FileUploader;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class ArticleController extends Controller
{
    /**
     *
     * @Route("/article/add", name="addArticle")
     *
     */
    public function addArticle(Request $request, FileUploader $fileUploader)
    {
        //seul un utilisateur connecté peut poster un article
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $article = new Article();
        $form = $this->createForm(ArticleUserType::class, $article);
        $form->handleRequest($request);
        //si le formulaire a été envoyé et si les données sont valides
        if ($form->isSubmitted() && $form->isValid()) {

            // ici on charge le formulaire de remplir notre objet article avec ces données
            $article = $form->getData();

            // $files va contenir l'image envoyée
            $file = $article->getImage();

            //comme on permet à nos utilisateurs de ne pas envoyer d'image
            //on initialise $fileName
            $fileName = '';

            //si on a bien un fichier, on utilise notre service d'upload
            // upload l'image et renvoie le nom aléatoire
            if($file){
                $fileName = $fileUploader->upload($file);
            }

            // on met à jour la propriété image, qui doit contenir le nom
            // et pas l'image elle même
            $article->setImage($fileName);

            //l'utilisateur connecté est l'auteur
            $article->setUser($this->getUser());
            //la date de publication
            $article->setDatePubli(new \DateTime(date('Y-m-d H:i:s')));
            // maintenant, on peut supprimer l'article
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();
            //on crée un message flash
            $this->addFlash(
                'success',
                'Article ajouté !'
            );
            //on renvoie sur la liste des catégories par exemple
            return $this->redirectToRoute('articles_showAll');
        }
        return $this->render('article/add.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/article/{id}",
     *     name="article_show",
     *     requirements={"id":"\d+"}
     * )
     */
    public function show($id)
    {
        // $this->getDoctrine()
        //            ->getRepository(Article::class)
        //est la classe qui nous permet de manipuler l'entité article (= table article dans la base)
        //find($id) récupère une entrée par son id
        //$article est un objet de classe Article
        $article = $this->getDoctrine()
            ->getRepository(Article::class)
            ->find($id);

        //nous permet de renvoyer un message d'erreur si aucun id ne correspond
        if (!$article) {
            throw $this->createNotFoundException(
                'No article found for id ' . $id
            );
        }

        return $this->render('article/article.html.twig', array('article' => $article));

    }

    /**
     * @Route("/articles",
     *     name="articles_showAll"
     * )
     */
    public function showAll()
    {
        $articles = $this->getDoctrine()
            ->getRepository(Article::class)
            ->myFindAll();

        if (!$articles) {
            throw $this->createNotFoundException(
                'No article found in database'
            );
        }

        return $this->render('article/articles.html.twig', array('articles' => $articles));

    }

    /**
     * @Route("/articles-recents",
     *     name="articles_recents"
     * )
     */
    public function showRecents()
    {
        //on va appeler la méthode findAllPostedAfter() nouvellement créée dans notre repository
        $articles = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findAllPostedAfter('2000-01-01');
        //$articles est  un tableau de tableaux et non pas un tableau d'objets articles

        $articles2 = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findAllPostedAfter2('2000-01-01');
        //articles2 est un tableau d'objets articles

        return $this->render('article/articles.recents.html.twig', array(
            'articles' => $articles,
            'articles2' => $articles2
        ));

    }

    /**
     * @Route("/article/update/{id}",
     *     name="article_update",
     *     requirements={"id":"\d+"}
     * )
     */
    public function updateArticle(Article $article, Request $request, FileUploader $fileUploader)
    {
        //on vérifie que l'utilisateur peut modifier l'article = s'il en est l'auteur
        $this->denyAccessUnlessGranted('edit', $article);

        //on stocke le nom du fichier image au cas où aucun fichier n'ai été envoyé
        $fileName = $article->getImage();

        //on doit remplaçer le nom du fichier image par une instance de File représentant le fichier
        if($article->getImage()) {
            $article->setImage(
                new File($this->getParameter('image_directory') . '/' . $article->getImage())
            );
        }

        $form = $this->createForm(ArticleUserType::class, $article);

        $form->handleRequest($request);

        //si le formulaire a été envoyé et si les données sont valides
        if ($form->isSubmitted() && $form->isValid()) {

            // ici on charge le formulaire de remplir notre objet article avec ces données
            $article = $form->getData();

            if($article->getImage()) { //on ne fait le traitement de l'upload que si une image a été envoyée

                // $files va contenir l'image envoyée
                $file = $article->getImage();

                //on utilise notre service qui upload l'image, supprime l'ancienne image et renvoie le nom aléatoire
                $fileName = $fileUploader->upload($file, $fileName);

            }

            // on met à jour la propriété image, qui doit contenir le nom
            // et pas l'image elle même
            $article->setImage($fileName);

            // maintenant, on peut enregistrer ce nouvel article
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            //on crée un message flash
            $this->addFlash(
                'success',
                'Article modifié !'
            );

            //on renvoie sur la liste des catégories par exemple
            return $this->redirectToRoute('articles_showAll');
        }

        return $this->render('article/update.html.twig', array(
            'form' => $form->createView(),
            'image' => $fileName
        ));

    }

    /**
     * @Route("/article/delete/{id}",
     *     name="article_delete",
     *     requirements={"id":"\d+"}
     * )
     */
    public function deleteArticle(Article $article)
    {
        //on vérifie que l'utilisateur peut supprimer l'article = s'il en est l'auteur
        $this->denyAccessUnlessGranted('delete', $article);

        //récupération du manager
        $entityManager = $this->getDoctrine()->getManager();

        //Je veux supprimer cet article
        $entityManager->remove($article);

        //j'execute les requêtes
        $entityManager->flush();
        $this->addFlash(
            'warning',
            'Article supprimé !'
        );

        //on redirige sur la liste des 5 derniers articles
        return $this->redirectToRoute('articles_showAll');
    }
}

templates/article/add.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Ajout d'article{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h1>Ajout d'article</h1>
        {{ dump(form) }}
        {{ form_start(form) }}  {# permet de créer la balise <form> #}

       {# <div class="form-group">
            #}{# on peut générer le formulaire champ par champ pour pouvoir les customiser individuellement #}{#
            {{ form_label(form.article.title) }}  #}{# va générer le label du champ title #}{#
            {{ form_errors(form.article.title) }}   #}{# va générer la div qui contiendra les éventuelles erreurs #}{#
            {{ form_widget(form.article.title, {'attr': {'class' : 'form-control-lg', 'placeholder' : 'entrez un titre svp' }}) }}   #}{# va générer le champ title #}{#
        </div>
        #}{# On peut tout à fait rajouter du html, css... #}{#
        <div class="autre-classe">
        {{ form_row(form.article.content, {'label' : 'Contenu de cet article !!', 'attr' : {'class' : 'form-control-lg', 'placeholder' : 'soyez inventif svp' }}) }}
        #}{# va générer le label , les erreurs et le champ Content en une instruction #}{#
        </div>#}

        {{ form_end(form) }}   {# permet de fermer la balise <form> et d'ajouter tout les champs qui n'ont pas été générés avant #}
    </div>
{% endblock %}

templates/article/article.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Article | {{ article.title }}{% endblock %}

{% block content %}
    <h1>{{ article.title }}</h1>
    <small> publié par <a href="{{ path('userPage' , {id : article.user.id}) }}">{{ article.user.username }}</a>  le {{ article.datepubli|date('d/m/Y') }}</small>
    {% if article.image %}<img src="{{ asset('uploads/images/' ~ article.image) }}">{%  endif %}

    <p>{{ article.content }}</p>

    {% for tag in article.tags %}
    {{ tag.libelle }} |
    {% endfor %}

{% endblock %}

templates/article/articles.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Articles | all{% endblock %}

{% block content %}

    {# pour afficher tout type de message flash #}
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ label }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    {# affichage des articles #}
    {% for article in articles %}
        <h1><a href="{{ path('article_show', {id:article.id}) }}">{{ article.title }}</a></h1>
        <small> publié par {{ article.user.username }} le {{ article.datepubli|date('d/m/Y') }}</small>
        <p>{{ article.content }}</p>
    {% endfor %}

{% endblock %}

templates/article/articles.recents.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Articles | all{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                {{ dump(articles) }}
                {% for article in articles %}
                    <h1>{{ article.title }}</h1>
                    {#
                        articles étant un tableau de tableaux, on a accède aux infos de l'utilisateur depuis article :
                        article.username, article.email
                    #}
                    <small> publié par {{ article.username }} le {{ article.date_publi|date('d/m/Y') }}</small>
                    <p>{{ article.content }}</p>
                {% endfor %}
            </div>

            <div class="col-md-6">
                {{ dump(articles2) }}
                {% for article in articles2 %}
                    <h1><a href="{{ path('article_show', {id: article.id}) }}">{{ article.title }}</a></h1>
                    {#
                        articles étant un tableau d'objets, on a article.user
                        user étant lui aussi un objet, on fait article.user.username ou article.user.email
                    #}
                    <small> publié par {{ article.user.username }} le {{ article.datePubli|date('d/m/Y') }}</small>
                    <p>{{ article.content }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'src/Controller/ArticleController.php'|file_link(0) }}">src/Controller/ArticleController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'templates/article/index.html.twig'|file_link(0) }}">templates/article/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/article/update.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Modification d'article{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <h1>Modification d'article</h1>
                {{ form_start(form) }}  {# permet de créer la balise <form> #}



                {{ form_end(form) }}   {# permet de fermer la balise <form> et d'ajouter tout les champs qui n'ont pas été générés avant #}
            </div>
            <div class="col-md-4">
                {% if image %}<img src="{{ asset('uploads/images/' ~ image) }}" class="img img-thumbnail">{%  endif %}
            </div>
        </div>
    </div>
{% endblock %}